name: Build & Deploy to Railway

on:
  push:
    branches:
      - main   # Trigger workflow on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (required for building images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build & push Docker image
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:latest

      # 5. Install Railway CLI & deploy
      - name: Install & Deploy to Railway
        run: |
          curl -sSL https://cli.railway.app/install.sh | sh
          export PATH=$PATH:$HOME/.railway/bin
          railway login --apiKey ${{ secrets.RAILWAY_API_TOKEN }}
          railway up --detach





































