deploy-to-railway:
  runs-on: ubuntu-latest
  needs: build-and-push

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Railway CLI
      shell: bash
      run: |
        curl -sL https://cli.railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH

    - name: Railway login
      shell: bash
      run: railway login --ci ${{ secrets.RAILWAY_API_TOKEN }}

    - name: Deploy Wisecow
      shell: bash
      run: railway up --service wisecow --detach



























