name: Wisecow CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build and push Docker image
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:latest

      # 4. Install Railway CLI
      - name: Install Railway CLI
        run: curl -sL https://cli.railway.app/install.sh | sh

      # 5. Login to Railway (CI mode)
      - name: Railway login
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway login --ci $RAILWAY_API_TOKEN

      # 6. Deploy to Railway
      - name: Deploy Wisecow
        run: railway up --service wisecow --detach



























