deploy-to-railway:
  runs-on: ubuntu-latest
  needs: build-and-push

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Railway CLI
      run: |
        curl -sL https://cli.railway.app/install.sh | sh
        export PATH=$PATH:$HOME/.railway/bin

    - name: Railway login
      env:
        RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
      run: railway login --ci $RAILWAY_API_TOKEN

    - name: Deploy Wisecow
      run: railway up --service wisecow --detach



























