name: CI/CD - Wisecow

on:
  push:
    branches:
      - main   # run workflow on commits to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:latest

  deploy-to-railway:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Railway
        run: |
          curl -sL https://cli.railway.app/install.sh | sh
          railway login --ci ${{ secrets.RAILWAY_API_TOKEN }}
          railway up --service wisecow --detach




































